services:
  app:
    build: .
    container_name: arena_one_app
    env_file:
      - .env.production
    restart: always
    ports:
      - "3000:3000"
    networks:
      - arenaone-network

  nginx:
    image: nginx:alpine
    container_name: arena_one_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    restart: always

networks:
  arenaone-network:
    external: true
