services:
  arenaone_app:
    build: .
    container_name: arenaone_app
    env_file:
      - .env.production
    restart: always
    ports:
      - "3000:3000"
    networks:
      - arenaone_network
    volumes:
      - arenaone_storage:/app/storage

  nginx:
    image: nginx:alpine
    container_name: arenaone_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - arenaone_storage:/var/www/arenaone_storage
    networks:
      - arenaone_network
    depends_on:
      - arenaone_app
    restart: always

networks:
  arenaone_network:
    external: true

volumes:
  arenaone_storage:
    name: arenaone_storage
    external: true
